<Project>
    
    <ItemGroup>
        <!-- Agrega el paquete StyleCop.Analyzers a todos los pryectos. -->
        <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    
    <ItemGroup>
        <!-- Integra el archivo stylecop.json a todos los pryectos. -->
        <AdditionalFiles Include="$(MSBuildThisFileDirectory)stylecop.json" Link="stylecop.json" />
    </ItemGroup>

</Project>