<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10"/>
        <PackageReference Include="Scalar.AspNetCore" Version="2.16.20" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\Records.Shared.Http\Records.Shared.Http.csproj" />
      <ProjectReference Include="..\..\Shared\Records.Shared.Serilog.DependencyInjection\Records.Shared.Serilog.DependencyInjection.csproj" />
      <ProjectReference Include="..\Records.Persons.Api.V1.Entities\Records.Persons.Api.V1.Entities.csproj" />
      <ProjectReference Include="..\Records.Persons.Shared.Configuration.DependencyInjection\Records.Persons.Shared.Configuration.DependencyInjection.csproj" />
    </ItemGroup>

</Project>
